Fix the following warning because of a missing prototype:
rse@en1:/e/apache/SRC/apache-1.3/src/modules/proxy
:> make
gcc -c  -I../../os/unix -I../../include   -funsigned-char -DSTATUS -pipe -O
-Wall -Wshadow -Wpointer-arith -Wcast-align -Wmissing-prototypes
-Wmissing-declarations -Wnested-externs -Winline `../../apaci` mod_proxy.c
mod_proxy.c: In function `proxy_handler':
mod_proxy.c:305: warning: implicit declaration of function `ap_die'
rm -f libproxy.a
ar cr libproxy.a mod_proxy.o  proxy_cache.o proxy_connect.o proxy_ftp.o
proxy_http.o proxy_util.o
ranlib libproxy.a


git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x@81849 13f79535-47bb-0310-9956-ffa450edef68